### ISSUE TITLE
The server says 'file' is now playing, however, no file sent to beamer.

### ISSUE THREAD

**Issue by calebbrgr** [DouweM/beamer-remote#1]
Please help me, I am not very good at coding or else I would fix this myself. The problem might be rake? The video file isn't being sent to beamer remotely on my mac, although, commands are being run under beamer-remote -F.
http://(SERVER)/Videos -> /play/Videos/Mushishi/01.mkv

Best,
cb

**Comment by DouweM** [comment]
@cheeberger I'm afraid it's been years since I last used Beamer or this tool, so it may very well have broken some time between then and now.

I recommend using https://plex.tv/ to browse and stream from your local video library from your Apple TV or any other device it supports.
